name: Android CI

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Run only JVM unit tests (faster & matches your current tests)
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace --info

      # Build a debug APK from the :app module
      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      # Upload test reports whether tests pass or fail
      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/reports/tests/testDebugUnitTest/
            **/build/test-results/testDebugUnitTest/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
